from rest_framework import viewsets, views
from rest_framework.generics import get_object_or_404
from rest_framework.decorators import action
from rest_framework.response import Response

from .serializers import PostSerializer, CommentSerializer
from .models import Post, Comment


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    # not listed in autogenerated API docs https://github.com/encode/django-rest-framework/issues/7468
    @action(methods=['post'], detail=True)
    def upvote(self, request, pk):
        post = get_object_or_404(Post, id=pk)
        post.upvotes += 1
        post.save()
        return Response(PostSerializer(post).data)


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer

